version: "3.8"
services:
  django:
    build: django/
    entrypoint: /app/docker-entrypoint.sh
    command: build
    volumes:
      - ./django/:/app:delegated
      - ./nginx-prod/build/:/build:delegated
      - ./logs/django:/app/logs:delegated
    environment:
      - BUILD=YES
    env_file:
      - ./secrets/scremsong-web.production.env
      - ./secrets/scremsong-web-db.dev.env
  frontend:
    image: node:16-alpine3.14
    entrypoint: /app/docker-entrypoint.sh
    command: build
    volumes:
      - ./frontend:/app:delegated
      - ./nginx-prod/build/:/build:delegated
    env_file:
      - secrets/scremsong-frontend.production.env
