version: "2"
services:
  nginx:
    build: keithmoss/scremsong-app:1
    volumes:
      - ./app:/app
      - ./logs/nginx:/var/log/nginx
      # - ./nginx/web:/var/www/html
    # depends_on:
    #   - web
    environment:
      - PRODUCTION=1
    ports:
      - "80:80"
      # - "8443:443"
