version: "2"
services:
  nginx:
    build: app/
    volumes:
      - ./app:/app
      # - ./nginx/web:/var/www/html
    # depends_on:
    #   - web
    environment:
      - DEVELOPMENT=1
    ports:
      - "80:3000"
      # - "8443:443"
