version: "2"
services:
  nginx:
    image: keithmoss/scremsong-app:2
    volumes:
      - ./app:/app
      - ./logs/nginx:/var/log/nginx
      # - ./nginx/web:/var/www/html
    # depends_on:
    #   - web
    environment:
      - PRODUCTION=1
    ports:
      - "80:80"
      - "443:443"
