version: "3.7"
services:
  db:
    image: mdillon/postgis:10-alpine
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=stack
    volumes:
      # Enable this mapping to inject the tweaked postgresql.conf file into our PostgreSQL container.
      - ./db/postgresql.conf:/etc/postgresql/postgresql.conf

      # Enable this mapping and create ./dev/pg_log/ to get easier access to PostgreSQL's log files for debugging.
      # - ./dev/pg_log/:/var/lib/postgresql/data/pg_log/

      # Enable this to store the PostgreSQL data on the host
      - ./db/data:/var/lib/postgresql/data

      - ./db/scripts:/var/lib/postgresql/scripts
  redis:
    image: bitnami/redis:6.2-debian-10
    ports:
      - "6379:6379"
    env_file:
      - secrets/redis.env
    volumes:
      - ./redis:/bitnami/redis/data
    # https://github.com/docker-library/redis/issues/35#issuecomment-360810072
    sysctls:
      net.core.somaxconn: "511"
  frontend:
    image: node:15.10.0-alpine3.12
    volumes:
      - ./frontend:/app:delegated
    entrypoint: /app/docker-entrypoint.sh
    ports:
      - "3000:3000"
    env_file:
      - secrets/scremsong-frontend.dev.env
  django:
    build: django/
    entrypoint: /app/docker-entrypoint.sh
    # command: supervisord
    volumes:
      - ./django/:/app:delegated
      - ./logs/scremsong-django:/app/logs:delegated
    ports:
      - "8000:8000"
    env_file:
      - secrets/scremsong-web.dev.env
      - secrets/scremsong-db.env
    depends_on:
      - db
      - redis
  python_rq_worker:
    build: django/
    entrypoint: /app/docker-entrypoint.sh
    command: python_rq_supervisord
    volumes:
      - ./django/:/app:delegated
    env_file:
      - secrets/scremsong-web.dev.env
      - secrets/scremsong-db.env
    depends_on:
      - db
      - redis
  rq_dashboard:
    build: rq-dashboard/
    entrypoint: /app/docker-entrypoint.sh
    volumes:
      - ./rq-dashboard/:/app:delegated
    ports:
      - "9181:9181"
    env_file:
      - secrets/scremsong-rq-dashboard.dev.env
    depends_on:
      - redis
  nginx:
    build: nginx/
    volumes:
      - ./nginx:/app
      - ./nginx/nginx/docker.https.dev.conf:/etc/nginx/conf.d/nginx.conf
      - ./keys/:/app/keys/:delegated
    depends_on:
      - django
      - rq_dashboard
      - frontend
    links:
      - django
    ports:
      - "443:443"
      - "8001:8001"
