version: "3.7"
services:
    db:
        image: mdillon/postgis:10-alpine
        #     command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=stack
    #     volumes:
    #         # Enable this mapping to inject the tweaked postgresql.conf file into our PostgreSQL container.
    #         - ./db/postgresql.conf:/etc/postgresql/postgresql.conf

    #         # Enable this mapping and create ./dev/pg_log/ to get easier access to PostgreSQL's log files for debugging.
    #         # - ./dev/pg_log/:/var/lib/postgresql/data/pg_log/

    #         # Enable this to store the PostgreSQL data on the host
    #         - ./db/data:/var/lib/postgresql/data
        build: django/
        entrypoint: /app/docker-entrypoint.sh
        command: build
        volumes:
            - ./django/:/app:delegated
            - ./build/:/build:delegated
        env_file:
            - secrets/scremsong-web.prod-local.env
            - secrets/scremsong-db.env
        depends_on:
            - db
