[tool.poetry]
name = "scremsong"
version = "0.1.0"
description = ""
authors = ["Keith Moss <keithamoss@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
Django = "^2.2.19"
psycopg2-binary = "^2.8.6"
djangorestframework = "^3.12.4"
django-cors-headers = "^3.7.0"
django-model-utils = "^4.1.1"
SQLAlchemy = "^1.4.15"
social-auth-app-django = "^4.0.0"
social-auth-core = "^4.1.0"
sentry-sdk = "^1.1.0"
redis = "^3.5.3"
tweepy = "^3.10.0"
django-celery-results = "^2.0.1"
daphne = "^3.0.2"
sh = "^1.14.2"
channels = "^3.0.3"
channels-redis = "^3.2.0"
celery = "^5.0.5"
gevent = "^21.1.2"
sqlalchemy = "^1.4.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
