[tool.poetry]
name = "scremsong"
version = "0.1.0"
description = ""
authors = ["Keith Moss <keithamoss@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
Django = "^3.2.8"
psycopg2-binary = "^2.9.1"
djangorestframework = "^3.12.4"
django-cors-headers = "^3.10.0"
django-model-utils = "^4.1.1"
SQLAlchemy = "^1.4.26"
social-auth-app-django = "^5.0.0"
social-auth-core = "^4.1.0"
sentry-sdk = "^1.4.3"
redis = "^3.5.3"
tweepy = "^4.1.0"
django-celery-results = "^2.2.0"
daphne = "^3.0.2"
sh = "^1.14.2"
channels = "^3.0.4"
channels-redis = "^3.3.1"
celery = "^5.1.2"
gevent = "^21.8.0"
sqlalchemy = "^1.4.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
