[tool.poetry]
name = "scremsong"
version = "0.1.0"
description = ""
authors = ["Keith Moss <keithamoss@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
Django = "4.0.4"
psycopg2-binary = "2.9.3"
djangorestframework = "3.13.1"
django-cors-headers = "3.12.0"
django-model-utils = "4.2.0"
sqlalchemy = "1.4.36"
social-auth-app-django = "5.0.0"
social-auth-core = "4.2.0"
sentry-sdk = "1.5.12"
redis = "4.3.1"
tweepy = "4.9.0"
django-celery-results = "2.3.1"
daphne = "3.0.2"
sh = "1.14.2"
channels = "3.0.4"
channels-redis = "3.4.0"
celery = "5.2.6"
gevent = "21.12.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"