[tool.poetry]
name = "scremsong"
version = "0.1.0"
description = ""
authors = ["Keith Moss <keithamoss@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
Django = "^4.0.1"
psycopg2-binary = "^2.9.3"
djangorestframework = "^3.13.1"
django-cors-headers = "^3.11.0"
django-model-utils = "^4.2.0"
SQLAlchemy = "^1.4.31"
social-auth-app-django = "^5.0.0"
social-auth-core = "^4.1.0"
sentry-sdk = "^1.5.3"
redis = "^4.1.0"
tweepy = "^4.4.0"
django-celery-results = "^2.2.0"
daphne = "^3.0.2"
sh = "^1.14.2"
channels = "^3.0.4"
channels-redis = "^3.3.1"
celery = "^5.2.3"
gevent = "^21.12.0"
sqlalchemy = "^1.4.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
