[tool.poetry]
name = "scremsong"
version = "0.1.0"
description = ""
authors = ["Keith Moss <keithamoss@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
Django = "4.1.2"
djangorestframework = "3.14.0"
django-cors-headers = "3.13.0"
django-model-utils = "4.2.0"
social-auth-core = "4.3.0"
social-auth-app-django = "5.0.0"
psycopg2-binary = "2.9.5"
SQLAlchemy = "1.4.42"
tweepy = "4.12.0"
channels = "3.0.5"
daphne = "3.0.2"
channels-redis = "3.4.1"
redis = "4.3.4"
sentry-sdk = "1.10.1"
sh = "1.14.3"
pytz = "2022.5"
rq = "1.10.1"
django-rq = "2.5.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"