version: "3.7"
services:
  flower_official_image:
    image: mher/flower
    entrypoint: /app/docker-entrypoint.sh
    volumes:
      - ./flower/:/app:delegated
      - ./django/:/django:delegated
    env_file:
      - secrets/scremsong-web.dev.env
    environment:
      - TZ=Australia/Perth
      # - FLOWER_PORT=8888
    ports:
      - 5555:5555
    depends_on:
      - celery_worker
  flower_our_own_image:
    build: django/
    entrypoint: /app/docker-entrypoint.sh
    command: flower
    volumes:
      - ./django/:/app:delegated
    env_file:
      - secrets/scremsong-web.dev.env
    ports:
      - 5555:5555
    depends_on:
      - db
      - redis
