# Generated by Django 2.0.6 on 2018-07-20 11:02

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import scremsong.app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialPlatforms',
            fields=[
                ('platform', models.TextField(choices=[(scremsong.app.models.SocialPlatformChoice('Twitter'), 'Twitter')], primary_key=True, serialize=False)),
                ('credentials', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
                ('active_app_uuid', models.CharField(editable=False, max_length=36, null=True)),
                ('pid', models.IntegerField(null=True)),
                ('errors', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True)),
                ('log', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
