# Generated by Django 2.0.6 on 2018-07-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='tweet_id',
            field=models.TextField(editable=False, unique=True),
        ),
    ]
