# Generated by Django 2.1.7 on 2019-03-27 12:29

from django.db import migrations, models
import scremsong.app.enums


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialassignments',
            name='close_reason',
            field=models.TextField(choices=[(scremsong.app.enums.SocialAssignmentCloseReason('Awaiting Reply'), 'Awaiting Reply'), (scremsong.app.enums.SocialAssignmentCloseReason('Map Updated'), 'Map Updated'), (scremsong.app.enums.SocialAssignmentCloseReason('No Change Required'), 'No Change Required'), (scremsong.app.enums.SocialAssignmentCloseReason('Not Relevant'), 'Not Relevant'), (scremsong.app.enums.SocialAssignmentCloseReason('Not Actioned'), 'Not Actioned')], default=None, null=True),
        ),
    ]
