# Generated by Django 2.1.7 on 2019-05-17 07:51

from django.db import migrations
import scremsong.app.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialplatforms',
            name='settings',
            field=scremsong.app.models.SocialPlatormsJSONField(blank=True, default=scremsong.app.models.default_socialplatform_settings),
        ),
    ]
