# Generated by Django 2.0.6 on 2018-06-22 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favourite_tables',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='recent_tables',
        ),
    ]
