# Generated by Django 2.0.6 on 2018-07-22 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180722_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialplatforms',
            name='active_app_uuid',
        ),
        migrations.RemoveField(
            model_name='socialplatforms',
            name='errors',
        ),
        migrations.RemoveField(
            model_name='socialplatforms',
            name='log',
        ),
        migrations.RemoveField(
            model_name='socialplatforms',
            name='pid',
        ),
    ]
