# Generated by Django 2.1.7 on 2019-03-31 04:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190327_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialcolumns',
            name='priority',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterUniqueTogether(
            name='socialcolumns',
            unique_together={('platform', 'priority')},
        ),
    ]
