# Generated by Django 3.1.7 on 2021-03-01 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_socialplatforms_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialassignments',
            name='thread_relationships',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='socialassignments',
            name='thread_tweets',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='socialcolumns',
            name='search_phrases',
            field=models.JSONField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='socialplatforms',
            name='credentials',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='source',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='twitterratelimitinfo',
            name='data',
            field=models.JSONField(),
        ),
    ]
