# Generated by Django 2.0.6 on 2018-07-15 04:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180622_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPlatforms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.TextField(choices=[('twitter', 'Twitter')])),
                ('credentials', django.contrib.postgres.fields.jsonb.JSONField()),
                ('active_app_uuid', models.CharField(editable=False, max_length=36, unique=True)),
                ('errors', django.contrib.postgres.fields.jsonb.JSONField()),
                ('log', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
