# Generated by Django 2.1.7 on 2019-03-31 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190331_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='column',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.SocialColumns'),
        ),
    ]
