# Generated by Django 2.0.6 on 2018-07-15 04:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import scremsong.app.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_socialplatforms_tweets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialplatforms',
            name='id',
        ),
        migrations.AlterField(
            model_name='socialplatforms',
            name='credentials',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='socialplatforms',
            name='errors',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='socialplatforms',
            name='log',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='socialplatforms',
            name='platform',
            field=models.TextField(choices=[(scremsong.app.models.SocialPlatformChoice('Twitter'), 'Twitter')], primary_key=True, serialize=False),
        ),
    ]
