# Generated by Django 2.0.6 on 2018-07-23 08:18

from django.db import migrations, models
import scremsong.app.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180722_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialColumns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.TextField(choices=[(scremsong.app.models.SocialPlatformChoice('Twitter'), 'Twitter')])),
                ('search_query', models.TextField()),
            ],
        ),
    ]
