# Generated by Django 2.1.7 on 2019-03-31 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_tweets_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialcolumns',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
