# Generated by Django 2.0.6 on 2018-07-15 05:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180715_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialplatforms',
            name='credentials',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
    ]
