# Generated by Django 2.0.6 on 2018-07-23 08:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_socialcolumns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialcolumns',
            name='search_query',
        ),
        migrations.AddField(
            model_name='socialcolumns',
            name='search_phrases',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None),
        ),
    ]
