# Generated by Django 2.0.6 on 2018-09-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180723_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='is_dismissed',
            field=models.BooleanField(default=False),
        ),
    ]
