# Generated by Django 4.0.3 on 2022-03-27 23:17

from django.db import migrations, models
import scremsong.app.enums


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_socialassignments_thread_relationships_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.TextField()),
                ('job_name', models.TextField()),
                ('job_func_name', models.TextField()),
                ('queue', models.TextField()),
                ('worker', models.TextField()),
                ('status', models.TextField(choices=[(scremsong.app.enums.TaskStatus['SUCCESS'], 'Success'), (scremsong.app.enums.TaskStatus['FAILED'], 'Failed')])),
                ('result', models.JSONField(blank=True, default=None, null=True)),
                ('meta', models.JSONField(blank=True, default=None, null=True)),
                ('job_args', models.JSONField(blank=True, default=None, null=True)),
                ('job_kwargs', models.JSONField(blank=True, default=None, null=True)),
                ('date_enqueued', models.DateTimeField()),
                ('date_done', models.DateTimeField()),
            ],
        ),
    ]
