# Generated by Django 4.0.3 on 2022-04-23 11:40

from django.db import migrations, models
import scremsong.app.enums


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_taskresults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='status',
            field=models.TextField(choices=[(scremsong.app.enums.TweetStatus['OK'], 'Ok'), (scremsong.app.enums.TweetStatus['DIRTY'], 'Dirty'), (scremsong.app.enums.TweetStatus['ARCHIVED'], 'Archived')]),
        ),
    ]
