# Generated by Django 2.1.7 on 2019-03-31 07:36

from django.db import migrations, models
import scremsong.app.enums


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190331_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='offline_reason',
            field=models.TextField(choices=[(scremsong.app.enums.ProfileOfflineReason('Disconnected'), 'Disconnected'), (scremsong.app.enums.ProfileOfflineReason('User Choice'), 'User Choice')], null=True),
        ),
    ]
