# Generated by Django 2.1.7 on 2019-03-31 09:19

from django.db import migrations
from scremsong.app.twitter import get_column_for_tweet_with_priority


def migrate_nuke_column_positions(apps, schema_editor):
    Profile = apps.get_model("app", "Profile")

    for p in Profile.objects.all():
        if "column_positions" in p.settings:
            del p.settings["column_positions"]
            p.save()


def migrate_populate_tweet_column_ids(apps, schema_editor):
    Tweets = apps.get_model("app", "Tweets")

    for t in Tweets.objects.all():
        if t.column_id is None:
            columnId = get_column_for_tweet_with_priority(t)
            if columnId is not None:
                t.column_id = columnId
                t.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_profile_offline_reason'),
    ]

    operations = [
        migrations.RunPython(migrate_nuke_column_positions),
        migrations.RunPython(migrate_populate_tweet_column_ids),
    ]
