# Generated by Django 2.0.6 on 2018-09-27 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180915_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_accepting_assignments',
            field=models.BooleanField(default=False),
        ),
    ]
