# Generated by Django 2.1.4 on 2018-12-15 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_profile_is_accepting_assignments'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='socialassignments',
            unique_together={('platform', 'social_id')},
        ),
    ]
