# Generated by Django 2.1.4 on 2018-12-21 01:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20181221_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialassignments',
            name='thread_tweets',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
    ]
