# Generated by Django 2.1.4 on 2018-12-22 07:40

from django.db import migrations, models
import scremsong.app.enums


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_socialassignments_thread_tweets'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='source',
            field=models.TextField(choices=[(scremsong.app.enums.TweetSource('Streaming'), 'Streaming'), (scremsong.app.enums.TweetSource('Backfill'), 'Backfill'), (scremsong.app.enums.TweetSource('Thread Resolution'), 'Thread Resolution')], default='Foobar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tweets',
            name='status',
            field=models.TextField(choices=[(scremsong.app.enums.TweetStatus('Ok'), 'Ok'), (scremsong.app.enums.TweetStatus('Dirty'), 'Dirty')], default='Foobar'),
            preserve_default=False,
        ),
    ]
