# Generated by Django 2.1.4 on 2018-12-22 11:27

from django.db import migrations, models
import scremsong.app.enums


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20181222_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='source',
            field=models.TextField(choices=[(scremsong.app.enums.TweetSource('Streaming'), 'Streaming'), (scremsong.app.enums.TweetSource('Backfill'), 'Backfill'), (scremsong.app.enums.TweetSource('Thread Resolution'), 'Thread Resolution'), (scremsong.app.enums.TweetSource('Testing'), 'Testing')]),
        ),
    ]
