# Generated by Django 2.1.4 on 2018-12-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_tweets_source'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tweets',
            index=models.Index(fields=['source'], name='app_tweets_source_02bee1_idx'),
        ),
        migrations.AddIndex(
            model_name='tweets',
            index=models.Index(fields=['status'], name='app_tweets_status_67c963_idx'),
        ),
    ]
