# Generated by Django 2.1.4 on 2018-12-24 02:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import scremsong.app.enums


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20181223_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={'queue_sort_by': scremsong.app.enums.ProfileSettingQueueSortBy(1)}),
        ),
    ]
