# Generated by Django 2.1.4 on 2018-12-24 02:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import scremsong.app.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_profile_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=scremsong.app.models.default_profile_settings),
        ),
    ]
