# Generated by Django 2.1.4 on 2018-12-27 10:06

from django.db import migrations, models
import scremsong.app.enums


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20181224_0236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweets',
            name='is_dismissed',
        ),
        migrations.AddField(
            model_name='tweets',
            name='state',
            field=models.TextField(choices=[(scremsong.app.enums.TweetState('Active'), 'Active'), (scremsong.app.enums.TweetState('Dealt With'), 'Dealt With'), (scremsong.app.enums.TweetState('Dismissed'), 'Dismissed')], default=scremsong.app.enums.TweetState('Active')),
        ),
    ]
