# Generated by Django 2.1.4 on 2018-12-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_socialassignments_assigned_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialassignments',
            name='last_updated_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
