# Generated by Django 2.1.4 on 2018-12-31 06:01

from django.db import migrations, models
import scremsong.app.enums


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20181228_0613'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetReplies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_text', models.TextField()),
                ('category', models.TextField(choices=[(scremsong.app.enums.TweetReplyCategories('Positive Report'), 'Positive Report'), (scremsong.app.enums.TweetReplyCategories('Negative Report'), 'Negative Report'), (scremsong.app.enums.TweetReplyCategories('Thank Yous'), 'Thank Yous')])),
            ],
        ),
    ]
