# Generated by Django 2.1.4 on 2018-12-31 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_tweetreplies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweetreplies',
            name='category',
        ),
    ]
