# Generated by Django 2.1.4 on 2018-12-31 06:07

from django.db import migrations, models
import scremsong.app.enums


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_tweetreplies_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetreplies',
            name='category',
            field=models.TextField(choices=[(scremsong.app.enums.TweetReplyCategories('Positive Report'), 'Positive Report'), (scremsong.app.enums.TweetReplyCategories('Negative Report'), 'Negative Report'), (scremsong.app.enums.TweetReplyCategories('Thank Yous'), 'Thank Yous')], null=True),
        ),
    ]
