# Generated by Django 2.1.4 on 2019-01-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_tweetreplies_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialassignments',
            name='last_read_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
