# Generated by Django 2.1.4 on 2019-01-02 05:00

from django.db import migrations, models
import scremsong.app.enums


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_socialassignments_last_read_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialassignments',
            name='status',
            field=models.TextField(choices=[(scremsong.app.enums.SocialAssignmentStatus('Pending'), 'Pending'), (scremsong.app.enums.SocialAssignmentStatus('Await Reply'), 'Await Reply'), (scremsong.app.enums.SocialAssignmentStatus('Closed'), 'Closed'), (scremsong.app.enums.SocialAssignmentStatus('Done'), 'Done')], default=scremsong.app.enums.SocialAssignmentStatus('Pending')),
        ),
    ]
