# Generated by Django 2.1.4 on 2019-01-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_allowedusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
