# Generated by Django 2.1.7 on 2019-03-17 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_socialcolumns_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialcolumns',
            old_name='user',
            new_name='assigned_to',
        ),
    ]
