# Generated by Django 2.1.7 on 2019-03-17 07:24

from django.db import migrations
import scremsong.app.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20190317_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='settings',
            field=scremsong.app.models.ProfileJSONField(blank=True, default=scremsong.app.models.default_profile_settings),
        ),
    ]
