# Generated by Django 2.1.7 on 2019-03-17 11:08

from django.db import migrations, models
import scremsong.app.enums


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20190317_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='state',
            field=models.TextField(choices=[(scremsong.app.enums.TweetState('Active'), 'Active'), (scremsong.app.enums.TweetState('Dealt With'), 'Dealt With'), (scremsong.app.enums.TweetState('Dismissed'), 'Dismissed'), (scremsong.app.enums.TweetState('Assigned'), 'Assigned')], default=scremsong.app.enums.TweetState('Active')),
        ),
    ]
