# Generated by Django 2.1.7 on 2019-03-23 07:23

from django.db import migrations
from scremsong.app.enums import SocialAssignmentStatus, SocialAssignmentCloseReason


def migrate_status_to_close_reason(apps, schema_editor):
    SocialAssignments = apps.get_model("app", "SocialAssignments")

    for assignment in SocialAssignments.objects.all():
        if assignment.status == SocialAssignmentStatus.AWAIT_REPLY:
            assignment.close_reason = SocialAssignmentCloseReason.AWAITING_REPLY
        elif assignment.status == SocialAssignmentStatus.CLOSED:
            assignment.close_reason = SocialAssignmentCloseReason.NOT_RELEVANT
        elif assignment.status == SocialAssignmentStatus.DONE:
            assignment.close_reason = SocialAssignmentCloseReason.MAP_UPDATED

        assignment.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_socialassignments_close_reason'),
    ]

    operations = [
        migrations.RunPython(migrate_status_to_close_reason),
    ]
