# Generated by Django 2.1.7 on 2019-03-23 07:37

from django.db import migrations, models
import scremsong.app.enums


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20190323_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialassignments',
            name='state',
            field=models.TextField(choices=[(scremsong.app.enums.SocialAssignmentState('Pending'), 'Pending'), (scremsong.app.enums.SocialAssignmentState('Closed'), 'Closed')], default=scremsong.app.enums.SocialAssignmentState('Pending')),
        ),
    ]
