# Generated by Django 2.1.7 on 2019-03-23 07:37

from django.db import migrations
from scremsong.app.enums import SocialAssignmentStatus, SocialAssignmentState


def migrate_status_to_state(apps, schema_editor):
    SocialAssignments = apps.get_model("app", "SocialAssignments")

    for assignment in SocialAssignments.objects.all():
        if assignment.status == SocialAssignmentStatus.PENDING:
            assignment.state = SocialAssignmentState.PENDING
        else:
            assignment.state = SocialAssignmentState.CLOSED

        assignment.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_socialassignments_state'),
    ]

    operations = [
        migrations.RunPython(migrate_status_to_state),
    ]
