# Generated by Django 2.1.7 on 2019-03-23 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20190323_0737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialassignments',
            name='status',
        ),
    ]
